server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
          #匹配后提供服务的路由地址
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE # 动态匹配服务调用
          predicates:
            - Path=/rest/payment/lb/** # 断言，路径相匹配的进行路由
            - After=2020-06-18T23:01:55.121+08:00[Asia/Shanghai] # 规定时间之后访问有效
            #- Before=2020-06-18T23:01:55.121+08:00[Asia/Shanghai]  # 规定时间之前访问有效
            #- Between=Between=2020-06-18T23:01:55.121+08:00[Asia/Shanghai], 2020-07-18T23:01:55.121+08:00[Asia/Shanghai]
#            - Cookie=username,ytz
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.ytz.com
            #- Method=GET
#            - Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
          # 过滤
          #filters:
          #  - AddRequestHeader=X-Request-red, blue
        - id: payment_route2
#          uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE # 动态匹配服务调用
          predicates:
            Path=/rest/payment/** #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/